### 0. NumPyのインポートをしてください.
インストールされていない場合、インストールしてください

In [1]:
import numpy as np

### 1. リストからNumPyの配列(numpy.ndarray)を作成し,出力してください.また,配列の形状,データ型についても確認してください.
リストは```[10, 20, 30, 40]```とします.

In [2]:
li = [10, 20, 30, 40]
x = np.array(li)
display(x)
display(x.shape)
display(x.dtype)

array([10, 20, 30, 40])

(4,)

dtype('int64')

### 2. ２つのリストから,ndarrayを作成し, 出力してください.また,配列の形状,データ型についても確認してください.
リストの1つ目は```[10, 20, 30, 40]```, 2つ目は```[1.0, 2.0, 3.0, 4.0]```とします.

In [3]:
li_1 = [10, 20, 30, 40]
li_2 = [1.0, 2.0, 3.0, 4.0]
x = np.array([li_1, li_2])
display(x)
display(x.shape)
display(x.dtype)

array([[10., 20., 30., 40.],
       [ 1.,  2.,  3.,  4.]])

(2, 4)

dtype('float64')

### 3. 以下の条件を元に２つのndarrayを作成し,出力してください.
- Numpyのarange関数を使い、1〜9までの数字（配列）を作成し、3×3の多次元配列に変換してください.
- Numpyのlinspace関数を使い、1〜10までの数字から等間隔の９つの数字で配列を作成し、3×3の多次元配列に変換してください.

In [4]:
x = np.arange(1, 10).reshape(3, 3)
y = np.linspace(1, 10, 9).reshape(3, 3)

display(x)
display(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

### 4. 3で作成した２つのndarrayを使い、加算、減算、乗算をし、出力してください.
乗算は行列積ではないことに注意

In [5]:
display(x + y)
display(x - y)
display(x * y)

array([[ 2.   ,  4.125,  6.25 ],
       [ 8.375, 10.5  , 12.625],
       [14.75 , 16.875, 19.   ]])

array([[ 0.   , -0.125, -0.25 ],
       [-0.375, -0.5  , -0.625],
       [-0.75 , -0.875, -1.   ]])

array([[ 1.  ,  4.25,  9.75],
       [17.5 , 27.5 , 39.75],
       [54.25, 71.  , 90.  ]])

In [6]:
# 参考: 行列積（Python3.5以降）
display(x @ y)

array([[ 33.   ,  39.75 ,  46.5  ],
       [ 72.375,  89.25 , 106.125],
       [111.75 , 138.75 , 165.75 ]])

### 5. 3で作成した２つのndarrayを使い、1つを9×1の多次元配列に変換してください.また、もう一つを１×9の多次元配列に変換してください.
なお、ndarray.reshape(9, 1) または　ndarray.reshape(1, 9)以外の方法で実現してください.

In [7]:
x = x.reshape(-1, 1)
y = y.reshape(1, -1)
display(x)
display(y)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

array([[ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
        10.   ]])

### 6. 5.で変換した２つのndarrayの次元数を確認してください.

In [8]:
display(x.ndim)
display(y.ndim)

2

2

### 7. 以下の処理を実行してください.
- リスト```[10, 20, 30, 40, 20, 20, 10, 70, 10, 30]```からndarrayを作成してください.
- 作成したndarrayのユニークな値を出力してください.

In [9]:
x = np.array([10, 20, 30, 40, 20, 20, 10, 70, 10, 30])
display(np.unique(x))

array([10, 20, 30, 40, 70])

### 8. ０で初期化されたndarrayを作成し、表示してください.
ただし、3×4のndarrayとしてください.また,データ型は問いません.

In [10]:
x = np.zeros(shape=(3, 4))
display(x)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 9. shapeが(3, 4)で要素が全て1のndarray及び、shapeが(3, 2)で要素が全て2のndarrayを作成し,出力してください.

In [11]:
x = np.ones((3, 4))
y = np.full((3, 2), 2)

display(x)
display(y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[2, 2],
       [2, 2],
       [2, 2]])

### 10. 9で作成した２つのndarrayを横（列方向）に結合して、出力してください.

In [12]:
# concatenateを使い、axisで結合する方向を指定する場合
z = np.concatenate([x, y], axis=1)
display(z)

array([[1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 2., 2.]])

In [13]:
# hstackを使う場合
z = np.hstack([x, y])
display(z)

array([[1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 2., 2.],
       [1., 1., 1., 1., 2., 2.]])

### 11. 0〜20までの数字から等間隔の12個の数字で配列(ndarray)を作成し、4×3の多次元配列に変換してください.その上で、2行目の要素にアクセスし、出力してください.

In [14]:
x = np.linspace(0, 20, 12).reshape(4, 3)
display(x[2,:])

array([10.90909091, 12.72727273, 14.54545455])

### 12. 1〜12までの数字でndarrayを作成し、3×4の多次元配列に変換してください.その上で、2列目の要素にアクセスし、出力してください.

In [15]:
x = np.arange(1, 13).reshape(3, 4)
display(x[:,1])

array([ 2,  6, 10])

### 13. 3×3の要素が全て0のndarrayを作成し、2行目, 1列目の要素を1に入れ替え、出力してください.

In [16]:
x = np.zeros(shape=(3, 3), dtype=np.int8)
x[1, 0] = 1
display(x)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]], dtype=int8)